import { PRODUCTS } from "./constants";

export type ProductConfig = { key: string; label: string; bonusLabel: string; enabled: boolean };
export type ColumnConfig = { key: string; label: string; visible: boolean };

export const DEFAULT_PRODUCTS: ProductConfig[] = PRODUCTS.map((p) => ({
  key: p.key,
  label: p.label,
  bonusLabel: p.bonusLabel,
  enabled: true,
}));

/** کلید فیلد جایزه هر کالا */
export const bonusKeyOf = (key: string) => `${key}_bonus`;

export const DEFAULT_COLUMNS: Record<string, ColumnConfig[]> = {
  pharmacies: [
    { key: "row", label: "ردیف", visible: true },
    { key: "repName", label: "نام نماینده", visible: true },
    { key: "dateShamsi", label: "تاریخ ثبت", visible: true },
    { key: "province", label: "استان", visible: true },
    { key: "city", label: "شهر", visible: true },
    { key: "region", label: "منطقه", visible: false },
    { key: "name", label: "نام داروخانه", visible: true },
    { key: "landline", label: "شماره ثابت", visible: false },
    { key: "managerName", label: "مسئول سفارش", visible: true },
    { key: "managerPhone", label: "شماره همراه", visible: true },
    { key: "address", label: "آدرس", visible: false },
    { key: "isPercent", label: "درصدی؟", visible: true },
    { key: "location", label: "لوکیشن", visible: true },
    { key: "nav", label: "مسیریابی", visible: true },
    { key: "sent", label: "وضعیت ارسال", visible: true },
  ],
  doctors: [
    { key: "row", label: "ردیف", visible: true },
    { key: "repName", label: "نام نماینده", visible: true },
    { key: "dateShamsi", label: "تاریخ ثبت", visible: true },
    { key: "province", label: "استان", visible: false },
    { key: "city", label: "شهر", visible: true },
    { key: "region", label: "منطقه", visible: false },
    { key: "name", label: "نام پزشک", visible: true },
    { key: "specialty", label: "تخصص", visible: true },
    { key: "phone", label: "شماره همراه پزشک", visible: true },
    { key: "secretaryName", label: "نام منشی", visible: false },
    { key: "secretaryPhone", label: "شماره منشی", visible: false },
    { key: "address", label: "آدرس مطب", visible: false },
    { key: "isPercent", label: "درصدی؟", visible: true },
    { key: "location", label: "لوکیشن", visible: true },
    { key: "nav", label: "مسیریابی", visible: true },
    { key: "sent", label: "وضعیت ارسال", visible: true },
  ],
  orders: [
    { key: "row", label: "ردیف", visible: true },
    { key: "repName", label: "نام نماینده", visible: true },
    { key: "dateShamsi", label: "تاریخ سفارش", visible: true },
    { key: "pharmacyName", label: "نام داروخانه", visible: true },
    { key: "managerName", label: "مسئول سفارش", visible: true },
    { key: "managerPhone", label: "شماره همراه", visible: true },
    { key: "address", label: "آدرس", visible: false },
    { key: "products", label: "اقلام سفارش", visible: true },
    { key: "distributor", label: "نام پخش", visible: true },
    { key: "visitor", label: "نام ویزیتور", visible: true },
    { key: "notes", label: "توضیحات", visible: false },
    { key: "location", label: "لوکیشن", visible: true },
    { key: "nav", label: "مسیریابی", visible: true },
    { key: "sent", label: "وضعیت ارسال", visible: true },
  ],
};

export const PERMISSION_GROUPS: {
  key: string;
  label: string;
  icon: string;
  items: { key: string; label: string }[];
}[] = [
  {
    key: "dashboard",
    label: "داشبورد",
    icon: "📊",
    items: [
      { key: "dashboard", label: "ورود به داشبورد" },
      { key: "dashboard.stats", label: "مشاهده آمار کلی (کارت‌های بالای صفحه)" },
      { key: "dashboard.activity", label: "مشاهده فعالیت لحظه‌ای نمایندگان" },
      { key: "dashboard.allReps", label: "مشاهده اطلاعات همه نمایندگان" },
      { key: "dashboard.export", label: "دانلود خروجی‌ها از داشبورد" },
    ],
  },
  {
    key: "pharmacy",
    label: "ثبت اطلاعات داروخانه",
    icon: "🏥",
    items: [
      { key: "pharmacy", label: "دسترسی به بخش داروخانه" },
      { key: "pharmacy.create", label: "ثبت داروخانه جدید" },
      { key: "pharmacy.view", label: "مشاهده لیست داروخانه‌ها" },
      { key: "pharmacy.viewAll", label: "مشاهده داروخانه‌های همه نمایندگان" },
      { key: "pharmacy.detail", label: "مشاهده جزئیات و لوکیشن" },
      { key: "pharmacy.location", label: "ثبت لوکیشن داروخانه" },
      { key: "pharmacy.percent", label: "ثبت/مشاهده وضعیت درصدی" },
      { key: "pharmacy.send", label: "ارسال اطلاعات به مدیر" },
      { key: "pharmacy.export", label: "خروجی اکسل داروخانه‌ها" },
      { key: "pharmacy.delete", label: "حذف رکورد داروخانه" },
    ],
  },
  {
    key: "doctor",
    label: "ثبت اطلاعات پزشک",
    icon: "🩺",
    items: [
      { key: "doctor", label: "دسترسی به بخش پزشک" },
      { key: "doctor.create", label: "ثبت پزشک جدید" },
      { key: "doctor.view", label: "مشاهده لیست پزشکان" },
      { key: "doctor.viewAll", label: "مشاهده پزشکان همه نمایندگان" },
      { key: "doctor.detail", label: "مشاهده جزئیات و لوکیشن" },
      { key: "doctor.location", label: "ثبت لوکیشن مطب" },
      { key: "doctor.percent", label: "ثبت/مشاهده وضعیت درصدی" },
      { key: "doctor.files", label: "بارگذاری فایل و عکس پزشک" },
      { key: "doctor.filesView", label: "مشاهده/دانلود/پرینت فایل‌ها" },
      { key: "doctor.send", label: "ارسال اطلاعات به مدیر" },
      { key: "doctor.export", label: "خروجی اکسل پزشکان" },
      { key: "doctor.delete", label: "حذف رکورد پزشک" },
    ],
  },
  {
    key: "order",
    label: "ثبت سفارشات داروخانه",
    icon: "🧾",
    items: [
      { key: "order", label: "دسترسی به بخش سفارشات" },
      { key: "order.create", label: "ثبت سفارش جدید" },
      { key: "order.view", label: "مشاهده لیست سفارشات" },
      { key: "order.viewAll", label: "مشاهده سفارشات همه نمایندگان" },
      { key: "order.detail", label: "مشاهده جزئیات سفارش" },
      { key: "order.items", label: "ثبت اقلام و جوایز" },
      { key: "order.location", label: "ثبت لوکیشن داروخانه" },
      { key: "order.send", label: "ارسال سفارش (و پیام‌رسان‌ها)" },
      { key: "order.export", label: "خروجی اکسل سفارشات" },
      { key: "order.delete", label: "حذف رکورد سفارش" },
    ],
  },
  {
    key: "field",
    label: "عملیات میدانی",
    icon: "🗺️",
    items: [
      { key: "trip", label: "ثبت تردد و ویزیت" },
      { key: "trip.start", label: "شروع/پایان ویزیت" },
      { key: "trip.pause", label: "ثبت وقفه در مسیر" },
      { key: "monitor", label: "رصد تردد نمایندگان" },
      { key: "home", label: "ثبت لوکیشن منزل" },
      { key: "home.viewAll", label: "مشاهده منزل همه نمایندگان" },
    ],
  },
  {
    key: "hr",
    label: "اداری و منابع انسانی",
    icon: "📝",
    items: [
      { key: "leave", label: "درخواست مرخصی" },
      { key: "leave.viewAll", label: "مشاهده مرخصی همه نمایندگان" },
      { key: "leaveApprove", label: "تایید/رد مرخصی" },
      { key: "leave.export", label: "خروجی اکسل مرخصی‌ها" },
    ],
  },
  {
    key: "reports",
    label: "گزارش‌ها",
    icon: "📈",
    items: [
      { key: "reports", label: "مشاهده گزارش ماهانه" },
      { key: "reports.allReps", label: "گزارش همه نمایندگان" },
      { key: "reports.products", label: "گزارش فروش هر قلم" },
      { key: "export", label: "دریافت خروجی اکسل" },
    ],
  },
  {
    key: "admin",
    label: "مدیریت سامانه",
    icon: "⚙️",
    items: [
      { key: "options", label: "افزودن مقادیر کشویی" },
      { key: "optionsDelete", label: "حذف مقادیر کشویی" },
      { key: "columns", label: "مدیریت ستون‌ها و کالاها" },
      { key: "users", label: "مدیریت کاربران" },
      { key: "users.password", label: "مشاهده رمز عبور کاربران" },
      { key: "users.permissions", label: "تغییر سطح دسترسی" },
      { key: "messengers", label: "تنظیم پیام‌رسان‌ها" },
      { key: "notifications.send", label: "ارسال اعلان به نمایندگان" },
    ],
  },
];

export const ALL_PERMISSION_KEYS = PERMISSION_GROUPS.flatMap((g) => g.items.map((i) => i.key));

export const REP_DEFAULT_PERMISSIONS = [
  "pharmacy",
  "pharmacy.create",
  "pharmacy.view",
  "pharmacy.detail",
  "pharmacy.location",
  "pharmacy.percent",
  "pharmacy.send",
  "doctor",
  "doctor.create",
  "doctor.view",
  "doctor.detail",
  "doctor.location",
  "doctor.percent",
  "doctor.files",
  "doctor.filesView",
  "doctor.send",
  "order",
  "order.create",
  "order.view",
  "order.detail",
  "order.items",
  "order.location",
  "order.send",
  "trip",
  "trip.start",
  "trip.pause",
  "home",
  "leave",
  "reports",
  "reports.products",
  "options",
];

export const SUPERVISOR_DEFAULT_PERMISSIONS = [
  ...REP_DEFAULT_PERMISSIONS,
  "dashboard",
  "dashboard.stats",
  "dashboard.activity",
  "dashboard.allReps",
  "dashboard.export",
  "pharmacy.viewAll",
  "pharmacy.export",
  "doctor.viewAll",
  "doctor.export",
  "order.viewAll",
  "order.export",
  "leave.viewAll",
  "leaveApprove",
  "leave.export",
  "home.viewAll",
  "monitor",
  "reports.allReps",
  "export",
];
