import { PRODUCTS } from "./constants";
export type ProductConfig = { key: string; label: string; bonusLabel: string; enabled: boolean };
export type ColumnConfig = { key: string; label: string; visible: boolean };
export type FormFieldConfig = { key: string; label: string; visible: boolean };
export const DEFAULT_PRODUCTS: ProductConfig[] = PRODUCTS.map((p) => ({
  key: p.key,
  label: p.label,
  bonusLabel: p.bonusLabel,
  enabled: true,
}));
/**      */
export const bonusKeyOf = (key: string) => `${key}_bonus`;
export const DEFAULT_FORM_FIELDS: Record<string, FormFieldConfig[]> = {
  pharmacies: [
    { key: "dateShamsi", label: " ", visible: true },
    { key: "province", label: "", visible: true },
    { key: "city", label: "", visible: true },
    { key: "region", label: "", visible: true },
    { key: "name", label: " ", visible: true },
    { key: "landline", label: "  ", visible: true },
    { key: "managerName", label: "  ", visible: true },
    { key: "managerPhone", label: "   ", visible: true },
    { key: "address", label: " ", visible: true },
    { key: "isPercent", label: " ", visible: true },
    { key: "files", label: "  ", visible: true },

    { key: "location", label: "   ", visible: true },
  ],
  doctors: [
    { key: "dateShamsi", label: " ", visible: true },
    { key: "province", label: "", visible: true },
    { key: "city", label: "", visible: true },
    { key: "region", label: "", visible: true },
    { key: "name", label: " ", visible: true },
    { key: "specialty", label: "", visible: true },
    { key: "phone", label: "  ", visible: true },
    { key: "secretaryName", label: " ", visible: true },
    { key: "secretaryPhone", label: "  ", visible: true },
    { key: "address", label: " ", visible: true },
    { key: "otherAddresses", label: "  ", visible: true },
    { key: "isPercent", label: " ", visible: true },
    { key: "files", label: "   ", visible: true },
    { key: "location", label: "   ", visible: true },
  ],
  orders: [
    { key: "dateShamsi", label: " ", visible: true },
    { key: "pharmacyName", label: " ", visible: true },
    { key: "managerName", label: "  ", visible: true },
    { key: "managerPhone", label: "   ", visible: true },
    { key: "address", label: " ", visible: true },
    { key: "location", label: "   ", visible: true },
    { key: "products", label: "   ", visible: true },
    { key: "distributor", label: " ", visible: true },
    { key: "visitor", label: " ", visible: true },
    { key: "notes", label: "", visible: true },
  ],
};
/**        */
export const AVAILABLE_FORM_FIELDS: Record<string, { key: string; label: string }[]> = Object.fromEntries(
  Object.entries(DEFAULT_FORM_FIELDS).map(([key, fields]) => [
    key,
    fields.map(({ key: fieldKey, label }) => ({ key: fieldKey, label })),
  ]),
);
export const DEFAULT_COLUMNS: Record<string, ColumnConfig[]> = {
  pharmacies: [
    { key: "row", label: "", visible: true },
    { key: "repName", label: " ", visible: true },
    { key: "dateShamsi", label: " ", visible: true },
    { key: "province", label: "", visible: true },
    { key: "city", label: "", visible: true },
    { key: "region", label: "", visible: false },
    { key: "name", label: " ", visible: true },
    { key: "landline", label: " ", visible: false },
    { key: "managerName", label: " ", visible: true },
    { key: "managerPhone", label: " ", visible: true },
    { key: "address", label: "", visible: false },
    { key: "isPercent", label: "", visible: true },
    { key: "location", label: "", visible: true },
    { key: "nav", label: "", visible: true },
    { key: "sent", label: " ", visible: true },
    { key: "actions", label: "", visible: true },
  ],
  doctors: [
    { key: "row", label: "", visible: true },
    { key: "repName", label: " ", visible: true },
    { key: "dateShamsi", label: " ", visible: true },
    { key: "province", label: "", visible: false },
    { key: "city", label: "", visible: true },
    { key: "region", label: "", visible: false },
    { key: "name", label: " ", visible: true },
    { key: "specialty", label: "", visible: true },
    { key: "phone", label: "  ", visible: true },
    { key: "secretaryName", label: " ", visible: false },
    { key: "secretaryPhone", label: " ", visible: false },
    { key: "address", label: " ", visible: false },
    { key: "isPercent", label: "", visible: true },
    { key: "location", label: "", visible: true },
    { key: "nav", label: "", visible: true },
    { key: "sent", label: " ", visible: true },
    { key: "actions", label: "", visible: true },
  ],
  orders: [
    { key: "row", label: "", visible: true },
    { key: "repName", label: " ", visible: true },
    { key: "dateShamsi", label: " ", visible: true },
    { key: "pharmacyName", label: " ", visible: true },
    { key: "managerName", label: " ", visible: true },
    { key: "managerPhone", label: " ", visible: true },

    { key: "address", label: "", visible: false },
    { key: "products", label: " ", visible: true },
    { key: "distributor", label: " ", visible: true },
    { key: "visitor", label: " ", visible: true },
    { key: "notes", label: "", visible: false },
    { key: "location", label: "", visible: true },
    { key: "nav", label: "", visible: true },
    { key: "sent", label: " ", visible: true },
    { key: "actions", label: "", visible: true },
  ],
};
export const PERMISSION_GROUPS: {
  key: string;
  label: string;
  icon: string;
  items: { key: string; label: string }[];
}[] = [
  {
    key: "dashboard",
    label: "",
    icon: "",
    items: [
      { key: "dashboard", label: "  " },
      { key: "dashboard.stats", label: "   (  )" },
      { key: "dashboard.activity", label: "   " },
      { key: "dashboard.allReps", label: "   " },
      { key: "dashboard.export", label: "   " },
    ],
  },
  {
    key: "pharmacy",
    label: "  ",
    icon: "",
    items: [
      { key: "pharmacy", label: "   " },
      { key: "pharmacy.create", label: "  " },
      { key: "pharmacy.view", label: "  " },
      { key: "pharmacy.viewAll", label: "   " },
      { key: "pharmacy.detail", label: "   " },
      { key: "pharmacy.location", label: "  " },
      { key: "pharmacy.percent", label: "/  " },
      { key: "pharmacy.send", label: "   " },
      { key: "pharmacy.export", label: "  " },
      { key: "pharmacy.delete", label: "  " },
    ],
  },
  {
    key: "doctor",
    label: "  ",
    icon: "",
    items: [
      { key: "doctor", label: "   " },
      { key: "doctor.create", label: "  " },
      { key: "doctor.view", label: "  " },
      { key: "doctor.viewAll", label: "   " },
      { key: "doctor.detail", label: "   " },
      { key: "doctor.location", label: "  " },
      { key: "doctor.percent", label: "/  " },
      { key: "doctor.files", label: "    " },
      { key: "doctor.filesView", label: "// " },
      { key: "doctor.send", label: "   " },
      { key: "doctor.export", label: "  " },
      { key: "doctor.delete", label: "  " },
    ],
  },
  {
    key: "order",
    label: "  ",
    icon: "",
    items: [
      { key: "order", label: "   " },
      { key: "order.create", label: "  " },
      { key: "order.view", label: "  " },
      { key: "order.viewAll", label: "   " },
      { key: "order.detail", label: "  " },
      { key: "order.items", label: "   " },
      { key: "order.location", label: "  " },
      { key: "order.send", label: "  ( )" },
      { key: "order.export", label: "  " },
      { key: "order.delete", label: "  " },
    ],
  },
  {
    key: "field",

    label: " ",
    icon: "",
    items: [
      { key: "trip", label: "   " },
      { key: "trip.start", label: "/ " },
      { key: "trip.pause", label: "   " },
      { key: "monitor", label: "  " },
      { key: "home", label: "  " },
      { key: "home.viewAll", label: "   " },
    ],
  },
  {
    key: "hr",
    label: "   ",
    icon: "",
    items: [
      { key: "leave", label: " " },
      { key: "leave.viewAll", label: "   " },
      { key: "leaveApprove", label: "/ " },
      { key: "leave.export", label: "  " },
    ],
  },
  {
    key: "reports",
    label: "",
    icon: "",
    items: [
      { key: "reports", label: "  " },
      { key: "reports.allReps", label: "  " },
      { key: "reports.products", label: "   " },
      { key: "export", label: "  " },
    ],
  },
  {
    key: "admin",
    label: " ",
    icon: "",
    items: [
      { key: "options", label: "  " },
      { key: "optionsDelete", label: "  " },
      { key: "columns", label: "   " },
      { key: "users", label: " " },
      { key: "users.password", label: "   " },
      { key: "users.permissions", label: "  " },
      { key: "messengers", label: " " },
      { key: "notifications.send", label: "   " },
    ],
  },
];
export const ALL_PERMISSION_KEYS = PERMISSION_GROUPS.flatMap((g) => g.items.map((i) => i.key));
export const REP_DEFAULT_PERMISSIONS = [
  "pharmacy",
  "pharmacy.create",
  "pharmacy.view",
  "pharmacy.detail",
  "pharmacy.location",
  "pharmacy.percent",
  "pharmacy.send",
  "doctor",
  "doctor.create",
  "doctor.view",
  "doctor.detail",
  "doctor.location",
  "doctor.percent",
  "doctor.files",
  "doctor.filesView",
  "doctor.send",
  "order",
  "order.create",
  "order.view",
  "order.detail",
  "order.items",
  "order.location",
  "order.send",
  "trip",
  "trip.start",
  "trip.pause",
  "home",
  "leave",
  "reports",
  "reports.products",
  "options",
];

export const SUPERVISOR_DEFAULT_PERMISSIONS = [
  ...REP_DEFAULT_PERMISSIONS,
  "dashboard",
  "dashboard.stats",
  "dashboard.activity",
  "dashboard.allReps",
  "dashboard.export",
  "pharmacy.viewAll",
  "pharmacy.export",
  "doctor.viewAll",
  "doctor.export",
  "order.viewAll",
  "order.export",
  "leave.viewAll",
  "leaveApprove",
  "leave.export",
  "home.viewAll",
  "monitor",
  "reports.allReps",
  "export",
];
/**      —       */
export const AVAILABLE_COLUMNS: Record<string, { key: string; label: string }[]> = {
  pharmacies: [
    { key: "row", label: "" },
    { key: "repName", label: " " },
    { key: "dateShamsi", label: " " },
    { key: "province", label: "" },
    { key: "city", label: "" },
    { key: "region", label: "" },
    { key: "name", label: " " },
    { key: "landline", label: " " },
    { key: "managerName", label: " " },
    { key: "managerPhone", label: " " },
    { key: "address", label: "" },
    { key: "isPercent", label: "" },
    { key: "percentValue", label: " " },
    { key: "location", label: "" },
    { key: "nav", label: "" },
    { key: "files", label: "" },
    { key: "sent", label: " " },
    { key: "createdAt", label: " " },
    { key: "actions", label: " (/)" },
  ],
  doctors: [
    { key: "row", label: "" },
    { key: "repName", label: " " },
    { key: "dateShamsi", label: " " },
    { key: "province", label: "" },
    { key: "city", label: "" },
    { key: "region", label: "" },
    { key: "name", label: " " },
    { key: "specialty", label: "" },
    { key: "phone", label: "  " },
    { key: "secretaryName", label: " " },
    { key: "secretaryPhone", label: " " },
    { key: "address", label: " " },
    { key: "otherAddresses", label: "  " },
    { key: "isPercent", label: "" },
    { key: "percentValue", label: " " },
    { key: "location", label: "" },
    { key: "nav", label: "" },
    { key: "files", label: "" },
    { key: "sent", label: " " },
    { key: "createdAt", label: " " },
    { key: "actions", label: " (/)" },
  ],
  orders: [
    { key: "row", label: "" },
    { key: "repName", label: " " },
    { key: "dateShamsi", label: " " },
    { key: "pharmacyName", label: " " },
    { key: "managerName", label: " " },
    { key: "managerPhone", label: " " },
    { key: "address", label: "" },
    { key: "products", label: " " },
    { key: "totalUnits", label: " " },
    { key: "totalBonus", label: " " },
    { key: "distributor", label: " " },
    { key: "visitor", label: " " },
    { key: "notes", label: "" },
    { key: "location", label: "" },
    { key: "nav", label: "" },

    { key: "sendStatus", label: " " },
    { key: "sent", label: " " },
    { key: "createdAt", label: " " },
    { key: "actions", label: " (/)" },
  ],
};
