name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render App
        run: curl -I  https://namayandeelmi-javad.onrender.com
